# Generated by Django 5.1 on 2025-10-04 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_flows",
                        to="users.company",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="expense",
            name="approval_flow_history",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenses_history",
                to="expenses.approvalflow",
            ),
        ),
        migrations.CreateModel(
            name="ApprovalFlowStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_number", models.IntegerField()),
                (
                    "approver_role",
                    models.CharField(
                        choices=[("MANAGER", "Manager"), ("ADMIN", "Admin")],
                        max_length=20,
                    ),
                ),
                (
                    "approval_flow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="expenses.approvalflow",
                    ),
                ),
            ],
            options={
                "ordering": ["step_number"],
            },
        ),
    ]
